language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("VarianceReducedSG")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
